version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: run tests
          command: |
            bundle exec rake test
workflows:
  version: 2
  run-tests:
    when: $CIRCLE_PULL_REQUEST
    jobs:
      - build
